"""The committed browser-compat-data snapshot, as plain sets.

``tests/data/compat.json`` is generated by ``scripts/gen_compat.py``; refresh
it with ``just compat``. Deriving these sets from it rather than transcribing
them by hand is the point: a missed entry becomes impossible instead of
invisible, since a test that silently covers 29 of 30 attributes still
passes.

The library keeps its own copies of some of this, in ``DEPRECATED_ELEMENTS``
and ``EXPERIMENTAL_ELEMENTS``, because it cannot read a test fixture at
runtime. ``tests/test_tags.py`` asserts the two agree.
"""

import json
import keyword
from pathlib import Path

SNAPSHOT = json.loads((Path(__file__).parent / "data" / "compat.json").read_text())

#: Where the snapshot came from, for a failure message worth reading.
SOURCE = "{package}@{version}".format(**SNAPSHOT["source"])

_ELEMENTS: dict[str, dict] = SNAPSHOT["elements"]

#: Every element MDN tracks, whatever its standing.
ELEMENTS = frozenset(_ELEMENTS)

DEPRECATED = frozenset(t for t, s in _ELEMENTS.items() if s["deprecated"])
EXPERIMENTAL = frozenset(t for t, s in _ELEMENTS.items() if s["experimental"])

#: Elements that are neither retired nor provisional: the set a page written
#: today should be built out of.
CURRENT = ELEMENTS - DEPRECATED - EXPERIMENTAL

#: Elements with no MDN page yet, so a docstring link would 404.
UNDOCUMENTED = frozenset(t for t, s in _ELEMENTS.items() if not s["mdn_url"])

GLOBAL_ATTRIBUTES = frozenset(SNAPSHOT["global_attributes"])

#: Every attribute name BCD tracks under an element, so `for`, `async`, and
#: the hyphenated ones are covered and not just the globals.
ELEMENT_ATTRIBUTES = frozenset(SNAPSHOT["element_attributes"])

#: Every attribute name under an SVG element, plus the SVG globals. Kept
#: apart from HTML because django-div builds inline SVG, and because "in"
#: and "from" are Python keywords that only turn up over here.
SVG_ATTRIBUTES = frozenset(SNAPSHOT["svg_attributes"])

#: Every attribute name a document can reach for, in either vocabulary.
ATTRIBUTES = GLOBAL_ATTRIBUTES | ELEMENT_ATTRIBUTES | SVG_ATTRIBUTES

#: The names that collide with a Python keyword, so a caller has to spell
#: them with a trailing underscore. The table in docs/building.md lists these.
KEYWORD_ATTRIBUTES = frozenset(a for a in ATTRIBUTES if keyword.iskeyword(a))
INPUT_TYPES = frozenset(SNAPSHOT["input_types"])
