"""Type stub for django_div.

Generated by scripts/gen_stub.py; regenerate with `just stub`.
"""

import re
from collections.abc import Callable, Iterator
from typing import Any, Literal

from pydantic import BaseModel

__version__: str

ATTR_NAME_RE: re.Pattern[str]
ATTR_OVERRIDES: dict[str, str]
BUILTIN_TAGS: frozenset[str]
DOCUMENT_ELEMENTS: frozenset[str]
ITEM_CLASSES: dict[str, type[HtmlItem]]
PARSERS: tuple[str, ...]
PRE_ELEMENTS: frozenset[str]
RAW_TEXT_ELEMENTS: frozenset[str]
TAG_CLASSES: dict[str, type[Tag]]
VOID_ELEMENTS: frozenset[str]

def best_parser() -> str: ...
def from_html(html: str, *, parser: str | None = None) -> Any: ...
def is_collection(value: Any) -> bool: ...
def marker() -> Callable[[str], str]: ...
def normalize_attr(name: str) -> str: ...
def parse(html: str, *, parser: str | None = None) -> list[HtmlItem]: ...
def tag_class(tag: str, *, name: str | None = None) -> type[Tag]: ...

class HtmlItem(BaseModel):
    def __html__(self) -> str: ...
    def render(self) -> str: ...

class Comment(HtmlItem):
    type: Literal["comment"]
    content: str

class Doctype(HtmlItem):
    type: Literal["doctype"]
    content: str

class Raw(HtmlItem):
    type: Literal["raw"]
    content: str

class Tag(HtmlItem):
    type: Literal["tag"]
    tag: str
    children: list[HtmlItem]
    attrs: dict[str, Any]
    def __init__(
        self, _tag: str | None = None, /, *children: Any, **attrs: Any
    ) -> None: ...
    @property
    def is_raw_text(self) -> bool: ...
    @property
    def is_void(self) -> bool: ...
    @property
    def text(self) -> str: ...
    @classmethod
    def model_validate(cls, obj: Any, **kwargs: Any) -> Tag: ...
    @classmethod
    def model_validate_json(cls, json_data: str | bytes, **kwargs: Any) -> Tag: ...
    def find(self, tag: str | None = None, **attrs: Any) -> Tag | None: ...
    def find_all(self, tag: str | None = None, **attrs: Any) -> list[Tag]: ...
    def iter_find(self, tag: str | None = None, **attrs: Any) -> Iterator[Tag]: ...
    def walk(self) -> Iterator[HtmlItem]: ...
    def render_raw_text(self) -> str: ...
    def __call__(self, *children: Any) -> Tag: ...

class Text(HtmlItem):
    type: Literal["text"]
    content: str

class A(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Abbr(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Address(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Area(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Article(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Aside(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Audio(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class B(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Base(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Bdi(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Bdo(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Blockquote(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Body(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Br(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Button(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Canvas(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Caption(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Cite(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Code(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Col(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Colgroup(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Data(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Datalist(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Dd(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Del(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Details(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Dfn(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Dialog(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Div(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Dl(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Dt(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Em(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Embed(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Fieldset(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Figcaption(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Figure(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Footer(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Form(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class H1(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class H2(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class H3(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class H4(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class H5(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class H6(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Head(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Header(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Hgroup(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Hr(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Html(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class I(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Iframe(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Img(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Input(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Ins(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Kbd(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Label(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Legend(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Li(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Link(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Main(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Map(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Mark(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Menu(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Meta(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Meter(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Nav(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Noscript(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Object(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Ol(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Optgroup(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Option(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Output(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class P(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Param(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Picture(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Pre(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Progress(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Q(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Rp(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Rt(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Ruby(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class S(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Samp(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Script(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Search(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Section(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Select(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Selectedcontent(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Slot(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Small(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Source(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Span(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Strong(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Style(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Sub(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Summary(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Sup(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Table(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Tbody(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Td(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Template(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Textarea(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Tfoot(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Th(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Thead(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Time(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Title(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Tr(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Track(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class U(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Ul(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Var(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Video(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

class Wbr(Tag):
    def __init__(self, *children: Any, **attrs: Any) -> None: ...

__all__ = [
    "A",
    "ATTR_NAME_RE",
    "ATTR_OVERRIDES",
    "Abbr",
    "Address",
    "Area",
    "Article",
    "Aside",
    "Audio",
    "B",
    "BUILTIN_TAGS",
    "Base",
    "Bdi",
    "Bdo",
    "Blockquote",
    "Body",
    "Br",
    "Button",
    "Canvas",
    "Caption",
    "Cite",
    "Code",
    "Col",
    "Colgroup",
    "Comment",
    "DOCUMENT_ELEMENTS",
    "Data",
    "Datalist",
    "Dd",
    "Del",
    "Details",
    "Dfn",
    "Dialog",
    "Div",
    "Dl",
    "Doctype",
    "Dt",
    "Em",
    "Embed",
    "Fieldset",
    "Figcaption",
    "Figure",
    "Footer",
    "Form",
    "H1",
    "H2",
    "H3",
    "H4",
    "H5",
    "H6",
    "Head",
    "Header",
    "Hgroup",
    "Hr",
    "Html",
    "HtmlItem",
    "I",
    "ITEM_CLASSES",
    "Iframe",
    "Img",
    "Input",
    "Ins",
    "Kbd",
    "Label",
    "Legend",
    "Li",
    "Link",
    "Main",
    "Map",
    "Mark",
    "Menu",
    "Meta",
    "Meter",
    "Nav",
    "Noscript",
    "Object",
    "Ol",
    "Optgroup",
    "Option",
    "Output",
    "P",
    "PARSERS",
    "PRE_ELEMENTS",
    "Param",
    "Picture",
    "Pre",
    "Progress",
    "Q",
    "RAW_TEXT_ELEMENTS",
    "Raw",
    "Rp",
    "Rt",
    "Ruby",
    "S",
    "Samp",
    "Script",
    "Search",
    "Section",
    "Select",
    "Selectedcontent",
    "Slot",
    "Small",
    "Source",
    "Span",
    "Strong",
    "Style",
    "Sub",
    "Summary",
    "Sup",
    "TAG_CLASSES",
    "Table",
    "Tag",
    "Tbody",
    "Td",
    "Template",
    "Text",
    "Textarea",
    "Tfoot",
    "Th",
    "Thead",
    "Time",
    "Title",
    "Tr",
    "Track",
    "U",
    "Ul",
    "VOID_ELEMENTS",
    "Var",
    "Video",
    "Wbr",
    "best_parser",
    "from_html",
    "is_collection",
    "marker",
    "normalize_attr",
    "parse",
    "tag_class",
]
