"""Generate src/django_div/__init__.pyi from the live module.

The element classes are created at runtime (``globals()[...] = cls`` in a
loop), which type checkers cannot see, so ``from django_div import Div`` is
an unresolved import without a stub. This script writes one that declares
every generated class, plus the real functions and constants, so pyright,
ty, and mypy resolve the whole public API.

Run it after changing ``_TAGS`` or the public API::

    just stub

``tests/test_stub.py`` asserts the committed stub matches this script's
output, so a stale stub fails CI.
"""

from __future__ import annotations

import sys
from pathlib import Path

import django_div

#: Everything in the stub except the generated element classes. Kept as
#: literal source so signatures stay reviewable; the sync test only guards
#: the parts that are derived (the element classes and ``__all__``).
STATIC = """\
import re
from collections.abc import Callable, Iterator
from typing import Any, Literal

from pydantic import BaseModel

__version__: str

ATTR_NAME_RE: re.Pattern[str]
ATTR_OVERRIDES: dict[str, str]
BUILTIN_TAGS: frozenset[str]
DOCUMENT_ELEMENTS: frozenset[str]
ITEM_CLASSES: dict[str, type[HtmlItem]]
PARSERS: tuple[str, ...]
PRE_ELEMENTS: frozenset[str]
RAW_TEXT_ELEMENTS: frozenset[str]
TAG_CLASSES: dict[str, type[Tag]]
VOID_ELEMENTS: frozenset[str]

def best_parser() -> str: ...
def from_html(html: str, *, parser: str | None = None) -> Any: ...
def is_collection(value: Any) -> bool: ...
def marker() -> Callable[[str], str]: ...
def normalize_attr(name: str) -> str: ...
def parse(html: str, *, parser: str | None = None) -> list[HtmlItem]: ...
def tag_class(tag: str, *, name: str | None = None) -> type[Tag]: ...

class HtmlItem(BaseModel):
    def __html__(self) -> str: ...
    def render(self) -> str: ...

class Comment(HtmlItem):
    type: Literal["comment"]
    content: str

class Doctype(HtmlItem):
    type: Literal["doctype"]
    content: str

class Raw(HtmlItem):
    type: Literal["raw"]
    content: str

class Tag(HtmlItem):
    type: Literal["tag"]
    tag: str
    children: list[HtmlItem]
    attrs: dict[str, Any]
    def __init__(
        self, _tag: str | None = None, /, *children: Any, **attrs: Any
    ) -> None: ...
    @property
    def is_raw_text(self) -> bool: ...
    @property
    def is_void(self) -> bool: ...
    @property
    def text(self) -> str: ...
    @classmethod
    def model_validate(cls, obj: Any, **kwargs: Any) -> Tag: ...
    @classmethod
    def model_validate_json(cls, json_data: str | bytes, **kwargs: Any) -> Tag: ...
    def find(self, tag: str | None = None, **attrs: Any) -> Tag | None: ...
    def find_all(self, tag: str | None = None, **attrs: Any) -> list[Tag]: ...
    def iter_find(self, tag: str | None = None, **attrs: Any) -> Iterator[Tag]: ...
    def walk(self) -> Iterator[HtmlItem]: ...
    def render_raw_text(self) -> str: ...
    def __call__(self, *children: Any) -> Tag: ...

class Text(HtmlItem):
    type: Literal["text"]
    content: str
"""


def build_stub() -> str:
    """The full stub text, derived from the imported module."""
    lines = [
        '"""Type stub for django_div.',
        "",
        "Generated by scripts/gen_stub.py; regenerate with `just stub`.",
        '"""',
        "",
        STATIC,
    ]
    for tag in sorted(django_div.BUILTIN_TAGS):
        cls = django_div.TAG_CLASSES[tag]
        lines.append(
            f"\nclass {cls.__name__}(Tag):\n"
            f"    def __init__(self, *children: Any, **attrs: Any) -> None: ...\n"
        )
    names = ",\n".join(f'    "{name}"' for name in sorted(django_div.__all__))
    lines.append(f"\n__all__ = [\n{names},\n]\n")
    return "".join(line if line.endswith("\n") else line + "\n" for line in lines)


def main() -> None:
    target = Path(__file__).parent.parent / "src" / "django_div" / "__init__.pyi"
    target.write_text(build_stub())
    print(f"wrote {target}", file=sys.stderr)


if __name__ == "__main__":
    main()
